# Generated by Django 4.0.3 on 2022-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetailsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('holiday_taken', models.IntegerField()),
                ('employee_email_id', models.CharField(max_length=50)),
                ('employee_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('author', models.IntegerField()),
                ('status', models.CharField(max_length=191)),
                ('resolved_by', models.IntegerField()),
                ('request_created_at', models.DateField()),
                ('vaccation_start_date', models.DateField()),
                ('vaccation_end_date', models.DateField()),
            ],
        ),
    ]
