# Generated by Django 4.0.3 on 2022-06-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesrequest',
            name='request_created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesrequest',
            name='resolved_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesrequest',
            name='vaccation_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeesrequest',
            name='vaccation_start_date',
            field=models.DateField(null=True),
        ),
    ]
